//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineTeknololoji.DAL1
{
    using System;
    using System.Collections.Generic;
    
    public partial class FotoTablo
    {
        public int FotoId { get; set; }
        public string FotoBaslik { get; set; }
        public string Foto { get; set; }
    }
}
