//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineTeknololoji.DAL1
{
    using System;
    using System.Collections.Generic;
    
    public partial class GonderimDetayTablo
    {
        public int GonderimDetayId { get; set; }
        public Nullable<int> UyeId { get; set; }
        public string Adres { get; set; }
        public string Ulke { get; set; }
        public string Sehir { get; set; }
        public string Durum { get; set; }
        public string PostaKodu { get; set; }
        public string SiparisId { get; set; }
        public Nullable<decimal> OdenenMiktar { get; set; }
        public string OdemeTipi { get; set; }
    
        public virtual Uyeler Uyeler { get; set; }
    }
}
