//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineTeknololoji.DAL1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SepetTablo
    {
        public int SepetId { get; set; }
        public Nullable<int> UrunId { get; set; }
        public Nullable<int> UyeId { get; set; }
        public Nullable<int> SepetDurumuId { get; set; }
    
        public virtual UrunTablo UrunTablo { get; set; }
    }
}
