//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineTeknololoji.DAL1
{
    using System;
    using System.Collections.Generic;
    
    public partial class UrunTablo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UrunTablo()
        {
            this.SepetTablo = new HashSet<SepetTablo>();
        }
    
        public int UrunId { get; set; }
        public string UrunIsim { get; set; }
        public Nullable<int> KategoriId { get; set; }
        public Nullable<bool> AktifMi { get; set; }
        public Nullable<bool> SilindiMi { get; set; }
        public Nullable<System.DateTime> OlusturmaTarihi { get; set; }
        public Nullable<System.DateTime> DegistirilmeTarihi { get; set; }
        public string UrunFoto { get; set; }
        public Nullable<bool> OzellikliMi { get; set; }
        public Nullable<int> Miktar { get; set; }
        public Nullable<decimal> Fiyat { get; set; }
    
        public virtual KategoriTablo KategoriTablo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SepetTablo> SepetTablo { get; set; }
    }
}
